print ("Mad libs where libs get mad.")
print ("Start below: \n\n")
time = input("Enter a number from 1 to 12: ")
noun = input ("Enter a noun (plural): ")
name = input ("Enter a name: ")
sentence = input("Enter any sentence: ")
verb = input("Enter a verb: ")
print ("\n\nThe story goes...\n\n")
print ("It was",time,"o'clock when I heared the knock at the door.")
#print ("I opened the door and there was a box full of" + noun "with a note saying from \"Mr.",name,".\"")
print ("I opened the door and there was a box full of " + noun + " with a note saying " + "From \"Mr. " + name.title() + ".\"")
print ("Just as I closed the door I heard a scream \"" + sentence.upper() + ".\"")
print ("I froze in place and all I could do was " +verb +"." )
